<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EREV332-PC" name="com.nostalgiaguy.testng.test.TestListenerExample" tests="6" failures="2" timestamp="5 Mar 2015 10:20:25 GMT" time="0.012" errors="0">
  <testcase name="t4" time="0.001" classname="com.nostalgiaguy.testng.test.TestListenerExample"/>
  <testcase name="t1" time="0.006" classname="com.nostalgiaguy.testng.test.TestListenerExample"/>
  <testcase name="t2" time="0.002" classname="com.nostalgiaguy.testng.test.TestListenerExample">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Method TestListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.TestListenerExample@4a62f5b] should have thrown an exception of class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.RuntimeException but got org.testng.TestException: 
Method TestListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.TestListenerExample@4a62f5b] should have thrown an exception of class java.lang.RuntimeException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.testng.TestException: 
Method TestListenerExample.t2()[pri:0, instance:com.nostalgiaguy.testng.test.TestListenerExample@4a62f5b] should have thrown an exception of class java.lang.RuntimeException
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1512)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 16 more
]]>
    </failure>
  </testcase> <!-- t2 -->
  <testcase name="t3" time="0.000" classname="com.nostalgiaguy.testng.test.TestListenerExample">
    <failure type="org.testng.TestNGException" message="
Method t3 requires 1 parameters but 0 were supplied in the @Test annotation.">
      <![CDATA[org.testng.TestNGException: 
Method t3 requires 1 parameters but 0 were supplied in the @Test annotation.
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:198)
	at org.testng.internal.Parameters.createParameters(Parameters.java:134)
	at org.testng.internal.Parameters.createParameters(Parameters.java:373)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:450)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1383)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1075)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1180)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- t3 -->
  <testcase name="t4" time="0.001" classname="com.nostalgiaguy.testng.test.TestListenerExample"/>
  <testcase name="t4" time="0.002" classname="com.nostalgiaguy.testng.test.TestListenerExample"/>
</testsuite> <!-- com.nostalgiaguy.testng.test.TestListenerExample -->
